-- VDL Table Tennis — Supabase schema
-- Run this once in the Supabase SQL editor (Dashboard -> SQL Editor).

-- ============ matches ============
create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  seq bigint generated by default as identity,
  date date not null,
  player1 text not null,
  player2 text not null,
  winner smallint not null check (winner in (1, 2)),
  -- score is for the record only; it never affects ratings
  score text,
  -- tournament label (e.g. 'Christmas 2024'); record keeping only
  tournament text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users (id)
);

create unique index if not exists matches_seq_idx on public.matches (seq);

-- ============ tournaments ============
create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  -- must match the tournament label stored on matches
  name text not null unique,
  date date not null,
  -- 'active' tournaments appear in the Add Match dropdown; mark 'completed' when done
  status text not null default 'active' check (status in ('active', 'completed')),
  -- planned draw: first-round slots in bracket order (JSON array, null entries = byes)
  bracket jsonb,
  created_at timestamptz not null default now()
);

insert into public.tournaments (name, date, status) values
  ('Christmas 2024', '2024-12-25', 'completed'),
  ('Christmas 2025', '2025-12-25', 'completed')
on conflict (name) do nothing;

-- ============ players (profile photos) ============
create table if not exists public.players (
  -- must match the player name used on matches
  name text primary key,
  -- small square JPEG data URL (resized client-side before upload)
  avatar text,
  updated_at timestamptz not null default now()
);

-- ============ profiles (roles) ============
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  role text not null default 'viewer' check (role in ('viewer', 'admin'))
);

-- Auto-create a viewer profile whenever a user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Helper used by RLS policies
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ============ row level security ============
alter table public.matches enable row level security;
alter table public.profiles enable row level security;
alter table public.tournaments enable row level security;
alter table public.players enable row level security;

-- Everyone can see profile photos; only admins can manage them
drop policy if exists "players are public to read" on public.players;
create policy "players are public to read"
  on public.players for select
  using (true);

drop policy if exists "admins can insert players" on public.players;
create policy "admins can insert players"
  on public.players for insert
  with check (public.is_admin());

drop policy if exists "admins can update players" on public.players;
create policy "admins can update players"
  on public.players for update
  using (public.is_admin());

drop policy if exists "admins can delete players" on public.players;
create policy "admins can delete players"
  on public.players for delete
  using (public.is_admin());

-- Everyone can read tournaments; only admins can manage them
drop policy if exists "tournaments are public to read" on public.tournaments;
create policy "tournaments are public to read"
  on public.tournaments for select
  using (true);

drop policy if exists "admins can insert tournaments" on public.tournaments;
create policy "admins can insert tournaments"
  on public.tournaments for insert
  with check (public.is_admin());

drop policy if exists "admins can update tournaments" on public.tournaments;
create policy "admins can update tournaments"
  on public.tournaments for update
  using (public.is_admin());

drop policy if exists "admins can delete tournaments" on public.tournaments;
create policy "admins can delete tournaments"
  on public.tournaments for delete
  using (public.is_admin());

-- Everyone (including anonymous visitors) can read matches
drop policy if exists "matches are public to read" on public.matches;
create policy "matches are public to read"
  on public.matches for select
  using (true);

-- Only admins can add / edit / delete matches
drop policy if exists "admins can insert matches" on public.matches;
create policy "admins can insert matches"
  on public.matches for insert
  with check (public.is_admin());

drop policy if exists "admins can update matches" on public.matches;
create policy "admins can update matches"
  on public.matches for update
  using (public.is_admin());

drop policy if exists "admins can delete matches" on public.matches;
create policy "admins can delete matches"
  on public.matches for delete
  using (public.is_admin());

-- Users can read their own profile (needed to resolve their role)
drop policy if exists "read own profile" on public.profiles;
create policy "read own profile"
  on public.profiles for select
  using (auth.uid() = id);

-- ============ promoting an admin ============
-- After someone signs up, promote them with:
--   update public.profiles set role = 'admin' where email = 'person@example.com';
